import { useScrollReveal } from '../../../hooks/useScrollReveal';
import { Hand, History, Route } from 'lucide-react';
import styles from './Strategies.module.css';

const MODES = [
  { icon:<Hand size={22}/>, tag:'Interactive', name:'Manual testing', desc:'Рухайте ціну руками, перевіряйте конкретні edge cases і дивіться, як реальний bot worker створює ордери, позицію та TP.', params:['Exact price control','Live orders and events'], bg:'linear-gradient(135deg,rgba(0,224,143,.18),rgba(0,224,143,.04))' },
  { icon:<Route size={22}/>, tag:'Repeatable', name:'Scenario testing', desc:'Зберігайте послідовності руху ціни та повторюйте той самий сценарій після змін алгоритму.', params:['Saved price paths','Pause and step mode'], bg:'linear-gradient(135deg,rgba(102,166,255,.15),rgba(102,166,255,.03))' },
  { icon:<History size={22}/>, tag:'Historical', name:'Bot backtesting', desc:'Оберіть існуючого бота й програйте реальні історичні свічки через той самий Bybit-compatible emulator.', params:['Orders on price chart','Equity, drawdown and exposure'], bg:'linear-gradient(135deg,rgba(185,140,255,.15),rgba(185,140,255,.03))' },
];
export default function Strategies(){const headerRef=useScrollReveal();const gridRef=useScrollReveal();return <section id="strategies" className={styles.strats}><div className="container"><div ref={headerRef} className="section-header reveal"><span className="eyebrow">Testing modes</span><h2 className="display-2">Один бот. <span className="italic-accent">Три рівні перевірки.</span></h2><p className="lead">Від ручного edge-case до багатомісячного історичного прогону без окремої спрощеної торгової логіки.</p></div><div ref={gridRef} className={`${styles.stratsGrid} reveal`}>{MODES.map((item)=><article key={item.name} className={`${styles.strat} glass-strong`} style={{'--bg':item.bg}}><div className={styles.stratIcon}>{item.icon}</div><span className={styles.stratTag}>{item.tag}</span><h3 className={styles.stratName}>{item.name}</h3><p className={styles.stratDesc}>{item.desc}</p><ul className={styles.stratParams}>{item.params.map((value)=><li key={value}><span className={styles.stratBullet}/>{value}</li>)}</ul></article>)}</div></div></section>}
