"""Common strategy interface used by the worker and service layer."""
from __future__ import annotations

from typing import Protocol

from app.models.trading_bot import TradingBot


class BotStrategy(Protocol):
    strategy_type: str

    def get_effective_settings(self, bot: TradingBot) -> dict: ...
    def get_runtime_state(self, db, bot: TradingBot) -> tuple[str, str | None]: ...
    def validate_start(self, db, bot: TradingBot) -> None: ...
    def tick(self, db, bot: TradingBot, *, force: bool = False) -> dict: ...
    def sync_orders(self, db, bot: TradingBot) -> list: ...
    def cancel_orders(self, db, bot: TradingBot) -> list: ...
    def get_position(self, db, bot: TradingBot) -> dict: ...
    def get_risk(self, db, bot: TradingBot) -> dict: ...
    def close_position(self, db, bot: TradingBot) -> dict: ...
